Nombre: Juan Felipe Fajardo Garzón

IA y Minirobots

Algorítmo genético para maximizar la función 𝑓(𝑥) = 𝑥 𝑠𝑒𝑛(10 𝜋 x) + 1, con 𝑥 ∈ [0,1]

Importar las librerías necesarias

In [ ]:
import numpy as np
import random
import math as mt

Inicialización de variables

In [ ]:
tam_arreglo = 20
n_poblacion = 100

Creacion de la población inicial

In [ ]:
def pob_ini():
  pob = np.array([np.random.randint(0, 2, (tam_arreglo)) for _ in range(n_poblacion)])
  return pob
print(pob_ini())

[[1 1 1 ... 0 1 1]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 1 0 0]
 ...
 [1 1 1 ... 1 1 0]
 [1 0 0 ... 1 0 1]
 [0 1 1 ... 0 0 1]]


Evaluación en la función a maximizar, primero se calcula el valor en decimal del arreglo, luego el valor x entre 0 y 1; finalmente se evalua ese valor x en la función

In [ ]:
def fun(pob):
  #Calculo del valor en decimal
  val_decimal = np.array([int(''.join(str(b) for b in pob[i]), 2) for i in range(n_poblacion)])
  #Calculo del valor en X ∈ [0,1]
  val_x = val_decimal/2**tam_arreglo
  #Calculo del fx
  fx = val_x*np.sin(10*np.pi*val_x)+1
  return fx,val_x

Calculo de la aptitud

In [ ]:
def aptitud(vals):
  max_val = vals.max()
  min_val = vals.min()
  if max_val == min_val:
    return np.zeros(len(vals))
  aptitudes = np.array([(vals[i] - min_val) / (max_val - min_val) for i in range(n_poblacion)])
  return aptitudes

Seleccion por ruleta

In [ ]:
def seleccion(pob,aptitud):
  new_seleccion = []
  probabilidades = aptitud / np.sum(aptitud)
  # ruleta acumulada
  ruleta = np.cumsum(probabilidades)
  for i in range(n_poblacion):
    # número aleatorio entre 0 y 1
    r = np.random.rand()

    # índice del individuo seleccionado
    seleccionado = np.searchsorted(ruleta, r, side='right')
    new_seleccion.append(pob[seleccionado])

  return np.array(new_seleccion)

Cruce de cromosomas

In [ ]:
def cruce(pob):
  new_gen =[]
  for z in range(0,n_poblacion,2):
    h = random.randint(2, tam_arreglo-2)
    hijo_1 = np.array(np.concatenate((pob[z][:h],pob[z+1][h:])))
    hijo_2 = np.array(np.concatenate((pob[z+1][:h],pob[z][h:])))
    new_gen.append(hijo_1)
    new_gen.append(hijo_2)
  return np.array(new_gen)

Mutación de los cromosomas

In [ ]:
def mutacion(pob):
  new_gen=np.copy(pob)
  r = np.random.randint(0, n_poblacion)
  c = np.random.randint(0, tam_arreglo)
  if new_gen[r][c] == 0:
    new_gen[r][c] = 1
  else:
    new_gen[r][c] = 0
  return new_gen

Ejecucion principal

In [ ]:
poblacion = pob_ini()

for i in range(20):
  fx_act = fun(poblacion)
  indice_mejor = np.argmax(fx_act[0])
  print("Generacion: ",i," el mejor cromosoma es ",poblacion[indice_mejor]," con un valor fx de: ",fun(poblacion)[0][indice_mejor])
  poblacion = seleccion(poblacion,aptitud(fun(poblacion)[0]))
  poblacion = cruce(poblacion)
  poblacion = mutacion(poblacion)
indice_mejor = np.argmax(fx_act[0])
print("Maximo de ",fun(poblacion)[0][indice_mejor]," encontrado en x = ",fun(poblacion)[1][indice_mejor]," con el cromosoma: ",poblacion[indice_mejor])

Generacion:  0  el mejor cromosoma es  [1 1 0 1 1 0 0 1 0 0 0 1 1 1 1 1 1 1 0 0]  con un valor fx de:  1.8466942600256449
Generacion:  1  el mejor cromosoma es  [1 1 0 1 1 0 0 1 0 0 0 1 1 1 1 1 0 1 1 1]  con un valor fx de:  1.8466820731896467
Generacion:  2  el mejor cromosoma es  [1 1 0 1 1 0 0 1 1 1 1 1 0 0 0 1 1 1 0 0]  con un valor fx de:  1.8505850938824355
Generacion:  3  el mejor cromosoma es  [1 1 0 1 1 0 1 0 0 0 0 0 0 0 0 1 0 0 1 1]  con un valor fx de:  1.850530929666693
Generacion:  4  el mejor cromosoma es  [1 1 0 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 1 1]  con un valor fx de:  1.8505283938505204
Generacion:  5  el mejor cromosoma es  [1 1 0 1 1 0 0 1 1 0 1 1 1 1 1 1 1 1 0 0]  con un valor fx de:  1.8504398889023448
Generacion:  6  el mejor cromosoma es  [1 1 0 1 1 0 1 0 0 0 0 1 0 1 1 0 1 1 1 1]  con un valor fx de:  1.8503752775700648
Generacion:  7  el mejor cromosoma es  [1 1 0 1 1 0 0 1 1 0 0 1 0 0 1 1 1 1 0 0]  con un valor fx de:  1.8499073941747426
Generacion:  8  el mejor 